version: '3.8'

services:
  rest-api:
    image: rest-api:v1
    container_name: rest-api
  postgres:
    image: postgres:17-alpine
    container_name: tasks_postgres
    environment:
      POSTGRES_DB: tasksdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U taskuser -d tasksdb"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
