name: Github actions test
on: [push]
env:
  REGISTRY: veberav
  IMAGE_NAME: rest-api
run-name: Build docker image
jobs:
  Build-docker-image:
    runs-on: ubuntu-24.04
    steps:
      - uses: priyesh2609/sha-trim-action@v1.1.2
        with:
          sha-length: 7
          env-name: 'TRIMMED_SHA'

      - name: Checkout commit
        uses: actions/checkout@v7.0.0
        with:
          ref: "${{ github.sha }}"

      #- name: Build docker image
      #  run: docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TRIMMED_SHA }}


      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v7
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TRIMMED_SHA }}

#  Push-image-to-docker-hub:
#    runs-on: ubuntu-24.04
#    environment: docker
#    needs:
#      - Build-docker-image
#    steps:
