name: Github actions test
on: [push]
run-name: Build docker image and deploy it via ssh
jobs:
  Builddocker-image:
    runs-on: ubuntu-24.04
    steps:
      - run: echo ${{ GITHUB_SHA }}
      - name: Checkout commit
        uses: actions/checkout@${{ GITHUB_SHA }}
