name: Github actions test
on: [push]
run-name: Build docker image
jobs:
  Builddocker-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout commit
        uses: actions/checkout@v7.0.0
        with:
          ref: "${{ github.sha }}"
